import type { JsonObject, RequireAtLeastOne } from "type-fest";

export type DateTime = string;

export interface CollectionItem {
  collectionId: string;
  collectionName: string;
}

export type FileableItem = RequireAtLeastOne<
  { id: string } & CollectionItem,
  "collectionId" | "collectionName"
>;

export interface CommonAutogeneratedProperties {
  id: string;
  created: DateTime;
  updated: DateTime;
}

export type Expand<T> = {
  expand: {
    [K in keyof T]: T[K][];
  };
};

export type Create<T> = Omit<
  T,
  keyof CollectionItem | keyof CommonAutogeneratedProperties
>;

export interface Sources extends CollectionItem, CommonAutogeneratedProperties {
  name: string;
  metadata?: JsonObject;
  type: "wearable" | "desktop" | "mobile" | "manual";
}

export interface Activity
  extends CollectionItem,
    Omit<CommonAutogeneratedProperties, "updated"> {
  source_id: string;
  start_time: DateTime;
  end_time: DateTime;
  activity_category:
    | "sleep"
    | "work"
    | "entertainment"
    | "idle"
    | "uncategorized";
  label?: string;
  payload?: JsonObject;
}
